# This is a basic workflow to help you get started with Actions

name: azelf testing

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Racket
        uses: Bogdanp/setup-racket@v0.13
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '8.7'

      - name: Install Dependencies
        run: raco pkg install --batch --auto

      - name: Run Testing
        run: raco test -x -p azelf
